# Generated by Django 2.2 on 2021-04-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='myBooks',
            field=models.ManyToManyField(related_name='myAuthors', to='books_authors_app.Book'),
        ),
    ]
